version : 2
jobs :
  build:
    docker :
      - image: docker:18.06.1-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: listprocess
          command: |
            docker build -t test .
            docker run -d -p 8080:8080 --name test_container test 
      - run :
          name : echo
          command : echo 'toto'