version : 2
jobs :
  build:
    docker :
      - image: docker:18.06.1-ce-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: BuildAndRun
          command: |
            docker build -t test .
            docker run -d -p 8080:8080 --name test_container test 
      

      - run :
          name : CurlContainer
          command : docker run --network container:test_container --name test_curl appropriate/curl --retry 10 --retry-connrefused http://localhost:8080